In [17]:
# imports
import pandas as pd
import re
from sklearn.model_selection import train_test_split

In [18]:
# load the data
fake = pd.read_csv("Fake.csv")
real = pd.read_csv("True.csv")

fake["label"] = 0
real["label"] = 1

df = pd.concat([fake, real], axis=0).reset_index(drop=True)

print(df.shape)
df.head()

(44898, 5)

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [19]:
# understand the data
print(fake.shape)
print(true.shape)

(23481, 5)
(21417, 5)

In [20]:
df["content"] = df["title"] + " " + df["text"]

In [ ]:
# remove unnecessary symbols
def clean_text(text):
    text = text.lower()
    text = re.sub(r'^.*?\(.*?\)\s?-\s?', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = re.sub(r"http\S+", "", text)   # remove URLs
    text = re.sub(r"\s+", " ", text)      # remove extra spaces
    return text

df["content"] = df["content"].apply(clean_text)

In [22]:
#keep only required columns
df = df[["content", "label"]]
df.head()

                                             content  label
0   donald trump sends out embarrassing new year’...      0
1   drunk bragging trump staffer started russian ...      0
2   sheriff david clarke becomes an internet joke...      0
3   trump is so obsessed he even has obama’s name...      0
4   pope francis just called out donald trump dur...      0

In [23]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [24]:
print(df["content"].iloc[0])

ben stein calls out 9th circuit court: committed a ‘coup d’état’ against the constitution 21st century wire says ben stein, reputable professor from, pepperdine university (also of some hollywood fame appearing in tv shows and films such as ferris bueller s day off) made some provocative statements on judge jeanine pirro s show recently. while discussing the halt that was imposed on president trump s executive order on travel. stein referred to the judgement by the 9th circuit court in washington state as a coup d tat against the executive branch and against the constitution. stein went on to call the judges in seattle political puppets and the judiciary political pawns. watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the executive order.read more trump news at: 21st century wire trump filessupport our work by subscribing & becoming a member @21wire.tv

In [25]:
#split the datasets
train_val_df, test_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df["label"]
)

train_df, val_df = train_test_split(
    train_val_df, test_size=0.2, random_state=42, stratify=train_val_df["label"]
)

print("Train:", len(train_df))
print("Val:", len(val_df))
print("Test:", len(test_df))

Train: 28734
Val: 7184
Test: 8980

In [26]:
train_df.to_csv("train.csv", index=False)
val_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)